
project_id = "nmpaafoonvivsdxcbaoe"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[realtime]
enabled = true

[edge_functions]
[edge_functions.shiprocket]
verify_jwt = false

[edge_functions.fixPermissions]
verify_jwt = false

[edge_functions.updateProducts]
verify_jwt = false

[edge_functions.verifyRazorpayPayment]
verify_jwt = false

[edge_functions.fixCouponPermissions]
verify_jwt = false

[edge_functions.createRazorpayOrder]
verify_jwt = false

[edge_functions.sendOrderNotification]
verify_jwt = false

[edge_functions.fixOrderPermissions]
verify_jwt = false

[edge_functions.verifyRazorpayOrder]
verify_jwt = false

[edge_functions.setupCouponRLS]
verify_jwt = false
